# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='alergia',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registro',
            name='anio',
            field=models.IntegerField(default=2016),
        ),
        migrations.AddField(
            model_name='registro',
            name='ciclista',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registro',
            name='cp',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='registro',
            name='dia',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='registro',
            name='duatlon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registro',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registro',
            name='email_ciclista',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registro',
            name='estado',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='registro',
            name='genero',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='registro',
            name='mes',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='registro',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
