# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_auto_20160804_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.CharField(blank=True, default=b'', max_length=50, unique=True),
        ),
    ]
