# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-15 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_auto_20161112_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.CharField(blank=True, default=b'', error_messages={b'unique': b'Alguien ya fue registrado con ese email'}, max_length=50, unique=True),
        ),
    ]
