# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-15 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
        ('registros', '0004_auto_20161115_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='municipio',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estado_municipio', to='municipios.Municipio'),
        ),
    ]
