# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-19 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_registro_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
