# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-23 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_registro_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.CharField(blank=True, default=b'', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='registro',
            unique_together=set([('genero', 'email')]),
        ),
    ]
