# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-23 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_auto_20161123_0155'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registro',
            unique_together=set([]),
        ),
    ]
