# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-19 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consecutivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llave', models.CharField(default=b'', max_length=7)),
                ('valor_inicial', models.IntegerField(default=1)),
                ('nombre_secuencia', models.CharField(default=b'', max_length=7)),
            ],
        ),
    ]
